[versions]
minecraft = "26.3"
fabric-loader = "0.19.5"
fabric-api = "0.161.0+26.3"
fabric-loom = "1.17-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-loom-plugin = { module = "net.fabricmc.fabric-loom:net.fabricmc.fabric-loom.gradle.plugin", version.ref = "fabric-loom" }
foojay-resolver-convention-plugin = { module = "org.gradle.toolchains.foojay-resolver-convention:org.gradle.toolchains.foojay-resolver-convention.gradle.plugin", version = "1.0.0" }
viafabricplus = { module = "com.viaversion:viafabricplus", version = "5.1.0" }
viabedrock = { module = "net.raphimc:ViaBedrock", version = "0.0.31-SNAPSHOT" }
minecraftauth = { module = "net.raphimc:MinecraftAuth", version = "5.0.2" }
netty-transport-raknet = { module = "dev.kastle.netty:netty-transport-raknet", version = "1.7.0" }
netty-transport-nethernet = { module = "org.cloudburstmc.netty:netty-transport-nethernet", version = "2.0.0.CR4-20260922.202324-5" }
libdatachannel-java-arch-detect = { module = "dev.opencollab:libdatachannel-java-arch-detect", version = "0.24.5.0-20260921.140330-12" }
